fix(conda.nu): use get to access sys host name
Change the way system host name is accessed when identifying the OS to
fix the following error:
Error: nu::shell::incompatible_path_access
  × Data cannot be accessed with a cell path
     ╭─[\nu_scripts\modules\virtual_environments\nu_conda_2\conda.nu:173:12]
 172 │ def windows? [] {
 173 │     ((sys).host.name | str downcase) == "windows"
     ·            ──┬─
     ·              ╰── string doesn't support cell paths
 174 │ }
     ╰────